### ISSUE TITLE
Problem with the search function of Facets 

### ISSUE THREAD

**Issue by DanielMayerthaler** [mmtrt/foobar2000#2]
Thanks TaqiRaza for your nice Foobar2000 snapcraft.io package.

Since the last update there is a problem with the search function of https://www.foobar2000.org/components/view/foo_facets, which I use for the comfortable cover navigation. In the screenshots you can see that probably because of a layout grid problem the search function of Facets doesn't have enough space. For testing I send my preferred interface theme "DMA-DeCenter OliB_v3b.fth". I hope this information can help for optimizing a future update of your important and aesthetically snapcraft.io package.

Best regards
Dani
[Facets Bug 221028.zip](https://github.com/mmtrt/foobar2000/files/9888797/Facets.Bug.221028.zip)

**Comment by mmtrt** [comment]
It seems newer version break facets so I've add older version to candidate branch where it works though I couldn't make it work in newer version because component is heavily outdated.

`snap refresh foobar2000 --candidate`

**Comment by DanielMayerthaler** [comment]
[DMA Radio v8.zip](https://github.com/mmtrt/foobar2000/files/9894204/DMA.Radio.v8.zip) Taqi Raza 
Thank you very much for the quick help. Your solution looks so much better than the original brownish default f2k. Here I send you my radio playlist with some lossless radio stations. Have a nice weekend
Dani
