### ISSUE TITLE
How do I add external drives? They dont show up in wine explorer. 

### ISSUE THREAD

**Issue by unheck** [mmtrt/foobar2000#5]

**Comment by mmtrt** [comment]
do you have connected `removable-media` if not then do

`sudo snap connect foobar2000:removable-media`


then browse mounted removable storage in /media, /run/media and /mnt

**Comment by unheck** [comment]
> do you have connected `removable-media` if not then do
> 
> `sudo snap connect foobar2000:removable-media`
> 
> then browse mounted removable storage on any of these paths `/media`, `/run/media` and `/mnt`

worked! thank you
