### ISSUE TITLE
Font too Small

### ISSUE THREAD

**Issue by Swift8641** [mmtrt/foobar2000#6]
Hello, I'm having an issue where foobar2000 displays the font too small. I was able to adjust the font size for certain elements using the in app preferences however the global font for things like the drop down menus and file browsing are still very small. Is there an option that I'm missing? 
![Screenshot from 2024-03-02 12-34-52](https://github.com/mmtrt/foobar2000/assets/111619933/9f1066ad-4436-4dc2-adb5-ab8aaac2a3b2)

**Comment by mmtrt** [comment]
Run this command `foobar2000.wine winecfg` and adjust dpi under graphics tab.

**Comment by Swift8641** [comment]
Thank you! This was exactly what I was looking for. This is what I get for not being familiar with wine :)
